# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dokumentation & Workflow Digitale Edition OIB
email: jdolhoff@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Rechercheergebnisse und Worflow
  zur Generierung einer Digitalen Edition
  am Orient Institut-Beirut
baseurl: "/documentation_digital-editions" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# author information
author: Julia Dolhoff

# Build settings

# Outputting
permalink:  /blog/:year/:month/:day/:title/ # default value: date; built-in values: date, pretty, ordinal, none
paginate_path: /page:num
timezone:    null
quiet:    false
# defaults: []
# excerpt_separator: <!--more-->

# Markdown
markdown: kramdown
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed

# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
